spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      dialect: 'org.hibernate.dialect.PostgreSQLDialect'
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
